assoc_homepage:
    path:     /
    defaults: { _controller: AssocBundle:Assoc:envoi }
    
assoc_listemembres:
    path:    /listemembres
    defaults: { _controller: AssocBundle:Assoc:listeMembres }

assoc_journal:
    path:    /journal
    defaults: { _controller: AssocBundle:Assoc:afficherJournal }

assoc_inscriptionnewsletter:
    path:    /inscriptionnewsletter
    defaults: { _controller: AssocBundle:Assoc:inscriptionNewsletter }

assoc_creerarticles:
    path:    /admin/articles
    defaults: { _controller: AssocBundle:Assoc:creerArticles }

assoc_editerarticles:
    path:    /admin/articles/edit/{id}
    defaults: { _controller: AssocBundle:Assoc:editerArticles }

assoc_supprimerarticles:
    path:    /admin/articles/supprime/{id}
    defaults: { _controller: AssocBundle:Assoc:supprimerArticles }

assoc_listeabonnes:
    path:    /listeabonnes
    defaults: { _controller: AssocBundle:Assoc:listeAbonnes }

assoc_envoisnewsletter:
    path:    /envoi
    defaults: { _controller: AssocBundle:Assoc:envoyerNewsletter }

assoc_unarticle:
    path:    /article/{id}
    defaults: { _controller: AssocBundle:Assoc:selectionnerUnArticle }
    
assoc_creerdon:
    path:   /creerdon
    defaults: { _controller: AssocBundle:Assoc:creerDon }

assoc_confirmerdon:
    path:   /confirmerdon
    defaults: { _controller: AssocBundle:Assoc:confirmerDon }
    
assoc_validerdon:
    path:   /validerdon/{id}
    defaults: { _controller: AssocBundle:Assoc:validerDon }
    
assoc_articlepdf:
    path:  /article/{id}/articleenpdf
    defaults: { _controller: AssocBundle:Assoc:genererArticleenPdf }

exportmembres_csv:
    path: /exportmembrecsv
    defaults: { _controller: AppBundle:Registration:exporterEnCsv }
    
exportabonnes_csv:
    path: /exportabonnescsv
    defaults: { _controller: AssocBundle:Assoc:exporterEnCsv }