services:
#    assoc.example:
#        class: AssocBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
   app_user_profile:
      class: AppBundle\Form\ProfileFormType
      arguments: [%fos_user.model.user.class%]
      tags:
         -  { name: form.type }
   assoc_lettre:
      class: AssocBundle\Form\LettreType
      

