services:
#    assoc.example:
#        class: AssocBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
   app_user_profile:
      class: AppBundle\Form\ProfileFormType
      tags:
            - { name: form.type, alias: app_user_profile }
   assoc_lettre:
      class: AssocBundle\Form\LettreType
   assoc_don:
       class: AssocBundle\Form\DonType
       tags:
           - { name: form.don }
      

