<?php

namespace AssocBundle\Repository;

/**
 * EffectuerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EffectuerRepository extends \Doctrine\ORM\EntityRepository
{
}
