<?php

namespace AssocBundle\Repository;

/**
 * LireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LireRepository extends \Doctrine\ORM\EntityRepository
{
}
